#!/usr/bin/env bash
set -euo pipefail

AUTHOR="Made by: envertex"
CONTACT="Contact: fabian.huamani@ucsm.edu.pe"

print_banner() {
  printf "%s\n%s\n\n" "$AUTHOR" "$CONTACT"
}

print_banner

DIRS=(recon exploit loot)

for d in "${DIRS[@]}"; do
  if [[ -d "$d" ]]; then
    echo "Folder exists: $d — aborting."
    exit 1
  fi
done

mkdir -p "${DIRS[@]}"

#touch loot/creds.txt

BASE="$(realpath .)"

echo "Workspace created at: $BASE"
echo "Files:"
echo "  - loot/creds.txt"
echo "Folders:"
for d in "${DIRS[@]}"; do
  echo "  - $d/"
done

exit 0
